<a href="https://colab.research.google.com/github/RogerThattt/-building-a-real-time-transaction-fraud-system/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Daily data usage in GB for 5 towers over 7 days
data_usage = np.array([
    [120, 135, 150, 145, 160, 155, 170],  # Tower 1
    [80, 95, 100, 105, 110, 115, 120],    # Tower 2
    [200, 210, 190, 195, 205, 220, 230],  # Tower 3
    [50, 60, 55, 65, 70, 75, 80],         # Tower 4
    [150, 160, 155, 165, 170, 175, 180]   # Tower 5
])

print("Data Usage Array:\n", data_usage)



Data Usage Array:
 [[120 135 150 145 160 155 170]
 [ 80  95 100 105 110 115 120]
 [200 210 190 195 205 220 230]
 [ 50  60  55  65  70  75  80]
 [150 160 155 165 170 175 180]]


In [2]:
# Total usage per day
total_per_day = np.add(data_usage[0], data_usage[1])
print("Total usage (Tower 1 + Tower 2) per day:", total_per_day)

# Difference between Tower 1 and Tower 2
diff = np.subtract(data_usage[0], data_usage[1])
print("Difference (Tower 1 - Tower 2) per day:", diff)


Total usage (Tower 1 + Tower 2) per day: [200 230 250 250 270 270 290]
Difference (Tower 1 - Tower 2) per day: [40 40 50 40 50 40 50]


In [3]:
# Scale Tower 3
scaled_tower3 = np.multiply(data_usage[2], 1.2)
print("Scaled Tower 3 Usage:", scaled_tower3)

# Normalize Tower 4
normalized_tower4 = np.divide(data_usage[3], data_usage[3].max())
print("Normalized Tower 4 Usage:", normalized_tower4)


Scaled Tower 3 Usage: [240. 252. 228. 234. 246. 264. 276.]
Normalized Tower 4 Usage: [0.625  0.75   0.6875 0.8125 0.875  0.9375 1.    ]


In [4]:
# Average usage per tower
avg_per_tower = np.mean(data_usage, axis=1)
print("Average usage per tower:", avg_per_tower)

# Median usage per tower
median_per_tower = np.median(data_usage, axis=1)
print("Median usage per tower:", median_per_tower)

# Standard deviation per day
std_per_day = np.std(data_usage, axis=0)
print("Standard deviation per day:", std_per_day)

# Variance per tower
var_per_tower = np.var(data_usage, axis=1)
print("Variance per tower:", var_per_tower)

# Min and Max usage per tower
min_per_tower = np.min(data_usage, axis=1)
max_per_tower = np.max(data_usage, axis=1)
print("Min usage per tower:", min_per_tower)
print("Max usage per tower:", max_per_tower)


Average usage per tower: [147.85714286 103.57142857 207.14285714  65.         165.        ]
Median usage per tower: [150. 105. 205.  65. 165.]
Standard deviation per day: [52.53570215 51.82663408 47.22287581 45.607017   47.49736835 49.75942122
 51.6139516 ]
Variance per tower: [234.69387755 155.10204082 170.40816327 100.         100.        ]
Min usage per tower: [120  80 190  50 150]
Max usage per tower: [170 120 230  80 180]
